### PR TITLE
use settings env directly

### PR DESCRIPTION
**Pull request by kr-g**
https://github.com/thonny/thonny/issues/2684

### CODE REVIEW

**Comment by kr-g** [comment]
https://github.com/thonny/thonny/issues/2684

**Comment by aivarannamaa** [comment]
Thanks for the suggestion!

These environment variables were meant mostly for the frontend process (and therefore would be inherited by the backend process as a side effect). 

I'm considering adding the possibility for specifying environment variables for current launch configuration as well.

**Comment by kr-g** [comment]
> I'm considering adding the possibility for specifying environment variables for current launch configuration as well.

having a additional text area ?
if you want to specify that more in detail and share your ideas i could offers some help here.

**Comment by kr-g** [comment]
i opened that issue because i continued to look at 
https://github.com/thonny/thonny/pull/2060

and debugged there again thonnys code and paramiko

**Pull request closed without merging**
