### PR TITLE
Add missing translation sites in editors.py.

### PR DESCRIPTION
**Pull request by nicolasdespres**
This PR adds missing translation sites in editors.py.

Those parts are not translated yet. I am looking forward to adding French translation for these sentences. When will they be available in poeditor.com ?

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thanks!

I'll try to upload new terms tonight

**Comment by aivarannamaa** [comment]
The new terms are now ready for translations at Poeditor

**Comment by nicolasdespres** [comment]
Thx for quickly publishing them. I have translated them to French. Cheers.

**Comment by aivarannamaa** [comment]
Great! I'll download updated translations before next release.

**Pull request merged**
