### PR TITLE
Sign script

### PR DESCRIPTION
**Pull request by nicolasdespres**
Hi,

First of all, thank you very much for developing Thonny. I have been using it for introducing Python to high-school students and it has worked seamlessly. Congrats!

One of the main issue my colleague and I have faced this year is ensuring students have done their homework... This problem is not related to Thonny but is general to all digital assignments with young students.

The solution I have found is to include a finger print based on the edit history (insertion and deletion) into each file. Such a finger print could be used to check slightly modified copied files, copy-paste, distinguish two students ending up with same content, etc...

I have tried to make it the least intrusive possible with the basic knowledge I have of Thonny's internal.

Best regards,

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thanks! Sounds interesting, but currently I find it a bit to follow your changes.

Could you please give me an short overview, about what will happen when the user edits or pastes code and how this helps detecting cheating?

For example, what happens, when the one student copies another student's work and makes some cosmetic changes to it? Can you detect cheating in this case?

I know that some teachers require students to turn in the action logs (https://github.com/thonny/thonny/wiki/User-action-logs). How would this compare to your approach?

**Comment by nicolasdespres** [comment]
Thanks for your reply !

I was not aware of the User-action-logs. The main difference I see with my approach is that the user action log is attached to a session whereas the finger print is related to a single file. In addition, the finger print is included in the python file, so there is no extra file to hand-in. Action log contains timestamp which I should probably add to the finger print.

The finger print is the edit action history, serialized in json, compressed and encoded in base64. It is then inserted as a comment at the end of the python script.

The idea is to collect the python files from all students and to run a "cheat" analysis tool on this collection (potentially including files from previous years too).

Copy-paste will appear as one big insert action.

Cosmetic change will most likely appear only as space/tabs/newline insertion.

Variable renames could be detected by checking if only characters belonging to variable names are deleted/inserted.

I have not developed such analysis tool yet. It will certainly need to be tweaked and checked against real-world data.

**Comment by aivarannamaa** [comment]
Have you considered publishing your work as Thonny's plug-in (https://github.com/thonny/thonny/wiki/Plugins)? It would give you more freedom in releasing the updates. You could take a look at https://github.com/thonny/thonny/issues/1751 for an example. It may be more inconvenient in places, but we could agree on introducing some new extension points, if required.
 
I don't rule out the possibility to include your work in Thonny's main code, but I don't want to do this before it feels useful and desirable for other teachers as well. In particular, the analysis tool should be publicly available.

**Comment by nicolasdespres** [comment]
Thanks for the tips. I will implement it as a plugin, and I will publish the analysis tool when it is ready. 

After some tests, I think I would need three extensions:
- a `EditorTextDestroyed` event as the opposite of the `EditorTextCreated` event. Currently only a sequence "<Button-1>" on the `EditorNotebook` is emitted.
- a save and load hooks to insert/extract the finger print

Without the `EditorTextDestroyed`, there is no clean way to detect when a tab is closed, and the plugin will leak some objects.

Without the save hook, the file will be written twice after a save (re-detecting the encoding and not taking advantage of the newline cleanup) and it won't work with remote file.

Without the load hook, the content of the `CodeViewText` widget will be reset twice.

Do you think these extensions are reasonable ?

I could try to implement them as a separate pull-request.

**Comment by aivarannamaa** [comment]
> Do you think these extensions are reasonable ?

Yes.

> I could try to implement them as a separate pull-request.

Please do! I'll wait with releasing version 3.3.12 until this.

**Comment by nicolasdespres** [comment]
Closed in favor to #1891

**Pull request closed without merging**
