### PR TITLE
[TRANS] Help Content translated to korean. Index files and titles each pages.

### PR DESCRIPTION
**Pull request by fabichoi**
Translated index page and titles each pages.
Descriptions of each pages will be translated until May, 2021.

### CODE REVIEW

**Comment by fabichoi** [comment]
@aivarannamaa is it wrong way to add translating help contents? let me know how to do merge master branch if you are okay.

**Comment by aivarannamaa** [comment]
Sorry for late reply!

I'm curious, why do you want to translate the titles without translating the main text? 

The downside of this partial translation is that whenever I update the main English text under thonny/plugins/help, the Korean users don't see it until you update the Korean copies. (Of course, it would be the same if you translated everything, but in that case the benefit of full Korean text might outweigh this.)

**Comment by aivarannamaa** [comment]
What about translating the index page only? In this case the user would see the latest content of the topic pages.

**Comment by fabichoi** [comment]
Oh.. I see what you meant. You think I should translate for all of help contents.
I'll translate all of help contents until end of this month. (April, 2021)
And then, leave a comment for PR again. 😃

**Comment by aivarannamaa** [comment]
> You think I should translate for all of help contents.

Either this, or translate only the index page.

**Comment by aivarannamaa** [comment]
> > You think I should translate for all of help contents.

> Either this, or translate only the index page.

... or only selected pages. My main idea was that once you create a new rst file under a locale, the users of this language stop automatically receiving updates made to the English rst.

**Comment by fabichoi** [comment]
@aivarannamaa I'm done with translating Korean for all of docs files. 
Can you check my tasks when you are not busy, please? 😄

**Comment by aivarannamaa** [comment]
Thanks! Unfortunately I don't know Korean so I can't grade your work, but I believe it's good :)

**Comment by fabichoi** [comment]
Thanks a lot! lol. I'll keep in touch this project and update translation to Korean :D

**Pull request merged**
