### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by be-we**

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thank you!

**Comment by aivarannamaa** [comment]
Are your translations here as well: https://poeditor.com/projects/po_edit?id_language=55&id=256075 ?

If not then it's recommended to import them there as well, otherwise next update may override yours.

**Comment by be-we** [comment]
@aivarannamaa The given link only leads to an error 404.

**Comment by aivarannamaa** [comment]
I see... Probably because you haven't logged in. You should join Thonny project on Poedit as described here: https://github.com/thonny/thonny/blob/master/docs/translate.md

**Comment by be-we** [comment]
@aivarannamaa Joining the Thonny project on POEditor has solved the error 404. Then I entered my translation updates into POEditor as well.

**Comment by aivarannamaa** [comment]
Great, thank you!

**Comment by Hermann12** [comment]
I have updated the translation and tested the .mo and  .po within thonny. Some translations are not taken? e.g. "Run current script" isn't into the .mo file why? I searche in the POEditor, but coudn't find. Also other menue text.

**Pull request merged**
