### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Hjarnor**
Ups. Just saw a little error and quickfixed it. Sry ;)

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thank you for the PR!

Do I understand correctly that you want to propose additions to Romanian translation? Did you export these files from POEditor?

Actually I'm usually exporting updated languages from POEditor before each release myself, so PR is not required. (I just noticed, that translate.md does suggest making a PR -- I'm changing it now)

**Comment by Hjarnor** [comment]
Yeah . I just saw that you replied with that at another pull request. Sry:D

sâm., 6 feb. 2021, 19:05 Aivar Annamaa <notifications@github.com> a scris:

**Comment by aivarannamaa** [comment]
No problem!

If you confirm that these files are exported from POEditor, then I can accept this PR.

**Comment by Hjarnor** [comment]
Yes they are exported from Poeditor.

sâm., 6 feb. 2021, 20:21 Aivar Annamaa <notifications@github.com> a scris:

**Pull request merged**
