### PR TITLE
reload all feature

### PR DESCRIPTION
**Pull request by kr-g**
this belongs to 

https://github.com/thonny/thonny/issues/1968

### CODE REVIEW

**Comment by kr-g** [comment]
only one file changed

https://github.com/thonny/thonny/pull/2375/commits/365906de2874d7d23703afda00de1b793f18978a

**Comment by aivarannamaa** [comment]
Thanks!

Please see https://github.com/thonny/thonny/issues/1968 and make the PR without unrelated features (env-file support)

**Comment by kr-g** [comment]
the env file... i dont know how it came inside...
of course i will remove it

**Comment by kr-g** [comment]
cleaned PR from unrelated source

RFC

**Comment by aivarannamaa** [comment]
Thank you for your effort, but please see https://github.com/thonny/thonny/issues/1968#issuecomment-1214401791 for explanation.

**Pull request closed without merging**
