### PR TITLE
More translatable strings + French L10N update

### PR DESCRIPTION
**Pull request by georgesk**
Hello,

I just worked this week-end on Debian's Thonny package (version 3.1.2), to make an I18N and a French L10N.

As it worked here, I went to the upstream site and saw that support for multiple languages was available, as a BETA feature, in the master branch. So, I merged changes which I worked out for the previous stable version into the development version (in a fork made very recently).

As far as I can tell (but I probably made mistakes), I marked as translatable all strings which deserved it, with the notable exceptions of strings submitted to logging functions: I suppose that developers will prefer to see log files written in a unique language. I am not sure about strings submitted to a serial communication.

Thank you for any suggestion.

Best regards,                       Georges

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thank you! It has been big work!

I'll review the changes and if everything looks OK, then I'll merge the PR. But I prefer keeping [Poeditor.com](https://poeditor.com/join/project/Gh188fdYH6) as main source for translations, ie. your po and mo files will be overwritten later. Fortunately, Poeditor supports importing translations, so your work on French translation won't be lost.

**Comment by aivarannamaa** [comment]
Looks like you have changed some places where concatenated string literals were marked as one translation unit. Now each line is marked separately. Did you do it for some specific purpose? IMO it's easier to translate if the lines are together.

**Comment by georgesk** [comment]
Dear Aivar,

Aivar Annamaa a écrit :
> Looks like you have changed some places where concatenated string literals were marked as one translation unit. Now each line is marked separately. Did you do it for some specific purpose? IMO it's easier to translate if the lines are together.

I did it mainly because I ignored whether gettext was able to deal with
concatenated string literals. I am used to manage strings with bare
gettext shell utilities. 

Probably if you highlight this issue, *python* gettext utilities are more
powerful and are able to reconstruct the concatenated string from the
source file to submit it as a whole to the translater, in a .pot or .po
file : am I wrong ?

Please feel free to cherry-pick whatever you want from my work. I shall
be happy to find it later for future Debian packages.

I want to try some additional l10n work : a French translation of the
documentation which can be browsed in views of the application. For this
purpose, I guess that it would be enough to patch the method load_rst_file
in class HelpView : if some language (eg. foo_BAZ) is known as preferred
by the user, load_rst_file("index.rst") should first try to find
"foo_BAZ/index.rst", and default to "index.rst" if nothing was found.

I shall try to make another pull request about it when something
exists whith some self-consistence.

Best regards,			Georges.

-- 
Georges KHAZNADAR et Jocelyne FOURNIER
22 rue des mouettes, 59240 Dunkerque France.
Téléphone +33 (0)3 28 29 17 70

**Comment by aivarannamaa** [comment]
> ... *python* gettext utilities are more powerful and are able to reconstruct the concatenated string from the source file to submit it as a whole to the translater, in a .pot or .po file

Yes, it looks like Babel (as used in #668) can reconstruct the concatenated strings.

> Please feel free to cherry-pick whatever you want from my work

I need to decide, whether it's easier to cherry pick or mark the strings myself. There are several places where I would change the way the strings are constructed, and in some places (eg. where the solution isn't stable) I would skip marking altogether.

> if some language (eg. foo_BAZ) is known as preferred by the user, load_rst_file("index.rst") should first try to find "foo_BAZ/index.rst", and default to "index.rst" if nothing was found.

Good idea! Can you please move current content from `thonny.plugins.help` under `thonny/locale/en_US` as well?

**Comment by aivarannamaa** [comment]
I'm rejecting this PR, because I would need to change too many of the markings (either by refactoring string construction in the original or by grouping concatenated strings as one unit or by skipping translation altogether). I believe I can import most of the content in your po-files into poeditor.com after I've marked more strings.

**Pull request closed without merging**
