### PR TITLE
Page down to end of shell text when focusing

### LINKED ISSUE #749: Focus shell option should bring you to a new prompt
Currently it just takes you back to where the editor cursor was in the shell.

However if I would like to efficiently flip between editing and running expressions, I would like to be able to press alt+S and immediately start typing a new expression to be evaluated.

Or optionally/alternately, be taken to the end of textline for a previously-typed but yet-to-be-evaluated expression, e.g

```
>>> a = [x[0] for x in some_script_function(argu
```
be brought to the end of the u, so I can finish writing it and hit enter (or hit ctrl+shift+left and delete everything to write a new expression).

If I had previously selected something to copy, or scrolled around some output, I don't want to be brought back to there with alt+S.

### PR DESCRIPTION
**Pull request by Ivoz**
Fixes #749

new at "Tkintering", I hope this is enough behaviour to work correctly. Unless you need something to add a prompt in some situations? 🤔 Not sure.

### CODE REVIEW

**Comment by aivarannamaa** [comment]
If you just want to put entry cursor to the end of the text and scroll into this location, then standard way to do this would be:

```
text.mark_set("insert", "end")
text.see("insert")
```

Would this work for your goal as well?

**Comment by Ivoz** [comment]
Sure. I was wondering if `perform_page_down` had any good error checking worth incorporating into that. If you think simpler is better than I won't disagree

**Comment by Ivoz** [comment]
Updated commit to reflect that

**Comment by Ivoz** [comment]
Also wondering if it would be handy to have a method to get the current shell in `Workbench`, similar to `self.get_editor_notebook()` / `self._editor_notebook` ? Or is it not there because shell could be "optional" and not shown / not instantiated?

**Comment by aivarannamaa** [comment]
> Also wondering if it would be handy to have a method to get the current shell in Workbench, similar to self.get_editor_notebook() / self._editor_notebook ? Or is it not there because shell could be "optional" and not shown / not instantiated?

It would be nice to have `get_shell` method, actually. At some point in time it would be too early to call it, but same applies to other methods as well. It's OK, to get and create the shell even if user has hidden it -- it just won't be shown then.

**Comment by aivarannamaa** [comment]
Thanks!

I forgot that there is `get_shell` in `thonny` module. I changed the code to use it.

**Pull request merged**
