### PR TITLE
Include the latest release in the AppData file

### PR DESCRIPTION
**Pull request by jwillikers**
This is just a small addition to the AppData file for Linux.
It just adds the details of the latest Thonny release.

### CODE REVIEW

**Comment by jwillikers** [comment]
Looks like the AppData for the 3.3.13 release contains this data but the `master` branch doesn't. However, I think that the AppData validating tool is upset about the hyperlinks in the description.  The following command will need to pass before Flathub will accept the Flatpak.
Here's the command with the notable output.

```
$ flatpak run org.freedesktop.appstream-glib validate thonny-flatpak-build-dir/files/share/appdata/org.thonny.Thonny.appdata.xml
thonny-flatpak-build-dir/files/share/appdata/org.thonny.Thonny.appdata.xml: FAILED:
• style-invalid         : <release> description should be prose and not contain hyperlinks [<p>This is minor technical update over 3.3.12. See https://github.com/thonny/thonny/releases/tag/v3.3.13 for more info</p>]
• style-invalid         : <release> description should be prose and not contain hyperlinks [<p>This is a bug-fix release. See https://github.com/thonny/thonny/releases/tag/v3.3.13 for more info</p>]
Validation of files failed
```

**Comment by jwillikers** [comment]
And I've updated the README to mention validating the AppData file. I removed the hyperlinks from the descriptions in the 3.3.13 release the XML is valid now.

**Comment by aivarannamaa** [comment]
Oops, I forgot to merge AppData updates from 3.3-fixes to master. Did it now.

**Comment by aivarannamaa** [comment]
Here is the submission: https://github.com/flathub/flathub/pull/2442

**Pull request merged**
