### PR TITLE
Added 'Save All' feature

### PR DESCRIPTION
**Pull request by hatlesshacker**
Ctrl-Alt-S now saves contents of all the opened editors

### CODE REVIEW

**Comment by aivarannamaa** [comment]
The content looks good, thanks!

About formatting -- it looks like you black-ed the code with different settings than specified in Thonny's https://github.com/thonny/thonny/blob/master/pyproject.toml 

These settings should kick in automatically. Can you please look into this?

**Comment by hatlesshacker** [comment]
I'm sorry, I was having trouble installing black. It's all well now!

**Comment by aivarannamaa** [comment]
Thanks!

There was still problem with formatting related to line length, but I fixed it myself (don't know why GitHub's check didn't catch this).

I also changed the mac shortcut for the new command

**Comment by hatlesshacker** [comment]
Great! :smiley:

**Pull request merged**
