### PR TITLE
translation updata

### PR DESCRIPTION
**Pull request by Dleta**
add&changed some words

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thanks!

**Comment by Dleta** [comment]
I have a question,is paragram tree equal to Abstact syntax tree(AST)????

**Comment by aivarannamaa** [comment]
> I have a question,is paragram tree equal to Abstact syntax tree(AST)????

Yes, I renamed AST to "Program tree", because I thought this would be more beginner-friendly.

**Comment by Dleta** [comment]
ok,ok

**Comment by Dleta** [comment]
hey,man.I get in puzzled in a script.I put the script in a non empty folder and run it ,but it's not I want.could you tell me why the filestree.txt different from the screenprint?(I want all the print write in filestree.txt)
------------------------------------------------
import os
import os.path
 
def dfs_showdir(path, depth):
    f = open('filestree.txt', 'w')
    if depth == 0:
        print("root:[" + path + "]")
        f.write("root:[" + path + "]\n")
 
    for item in os.listdir(path):
        if '.git' not in item:
            print("|      " * depth + "+--" + item)
            f.write("|      " * depth + "+--" + item + '\n')
 
            newitem = path +'/'+ item
            if os.path.isdir(newitem):
                dfs_showdir(newitem, depth +1)
    f.close()
 
if __name__ == '__main__':
    dfs_showdir('./', 0)
--------------------------------------

**Comment by Dleta** [comment]
oh god ,my code..........

**Comment by Dleta** [comment]
> ## hey,man.I get in puzzled in a script.I put the script in a non empty folder and run it ,but it's not I want.could you tell me why the filestree.txt different from the screenprint?(I want all the print write in filestree.txt)
> import os
> import os.path
> 
> def dfs_showdir(path, depth):
> f = open('filestree.txt', 'w')
> if depth == 0:
> print("root:[" + path + "]")
> f.write("root:[" + path + "]\n")
> 
> ```
> for item in os.listdir(path):
>     if '.git' not in item:
>         print("|      " * depth + "+--" + item)
>         f.write("|      " * depth + "+--" + item + '\n')
> 
>         newitem = path +'/'+ item
>         if os.path.isdir(newitem):
>             dfs_showdir(newitem, depth +1)
> f.close()
> ```
> 
> ## if **name** == '**main**':
> dfs_showdir('./', 0)
> 
> 
> 

oh my code...,see that picture.......

**Comment by Dleta** [comment]
> > I have a question,is paragram tree equal to Abstact syntax tree(AST)????
> 
> Yes, I renamed AST to "Program tree", because I thought this would be more beginner-friendly.

cool

**Pull request merged**
